name: SIYAM MASS REPORT ENGINE
on:
  workflow_dispatch:
    inputs:
      target_link:
        required: true
jobs:
  strike:
    runs-on: ubuntu-latest
    environment: Production  # আপনার পারমিশন ছাড়া শুরু হবে না
    steps:
      - name: High-Intensity Mass Reporting (500 Reports)
        run: |
          for i in {1..500}; do
            RANDOM_IP="103.$(($RANDOM%255)).$(($RANDOM%255)).$(($RANDOM%255))"
            curl -A "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)" \
            -H "X-Forwarded-For: $RANDOM_IP" \
            -L "${{ github.event.inputs.target_link }}" --silent --output /dev/null
          done
      - name: Mission Success
        run: |
          curl -s -X POST https://api.telegram.org/bot8032917202:AAFCD2hCP709BspRJSbibMl3BefYTVxV-qE/sendMessage \
          -d chat_id=7416528268 \
          -d text="✅ **MISSION ACCOMPLISHED!** %0A%0Aটার্গেট আইডিতে ৫০০টি বিডি-প্রক্সি রিপোর্ট পাঠানো হয়েছে।"
